Fix(web)/dispute overview component tweaks
kleros/kleros-v2 pull request #1428
Opened 2024-01-19 13:53 UTC by Harman-singh-waraich

Warning ⚠️  : Requires subgraph redeploy

This PR fixes :

1.  Removes hardcoded Alias UI from Verdict component.
2. Dispute Timeline now shows on evidence period.
3.  Dispute Timeline dates have been fixed, we now have a `timeline` field in `Round` entity , that maps the Period ends

2024-01-19 16:17 UTC, Harman-singh-waraich commented on web/src/components/Verdict/DisputeTimeline.tsx
> +            subtitle: `${formatDate(isOngoing ? previousRoundEnd : roundTimeline?.[Periods.vote])} / ${
yea makes sense 🤔 , will make like that

2024-01-22 16:21 UTC, alcercu approved these changes
lgtm

2024-01-22 16:22 UTC, alcercu requested changes
We are going to need to up the version of `subgraph/package.json` so it doesn't collide with the previous version when deploying

2024-01-23 15:45 UTC, alcercu submitted a review, later dismissed
lgtm

2024-01-23 16:28 UTC, merged