fix(web): Error message
kleros/kleros-v2 pull request #1583
Opened 2024-05-18 02:43 UTC by ShubhamParkhi

The changes in hook checks if the isAllowance flag is true. If it is, it sets an error message based on whether parsedAmount is zero or if there’s an allowanceError. If isAllowance is false, it does a similar check but for setStakeError instead.

Breakdown of the conditions:
- If parsedAmount is zero, it sets the error message to “Please enter a valid amount to stake or withdraw.”
- If there’s an allowanceError or setStakeError, it sets the error message to “There was an error processing your request. Please try again later.”

2024-05-20 16:15 UTC, kemuru requested changes
Errors do not go away when you interact with the InputDisplay Field, I think we should rethink this in another way. I think contract errors should not be displayed for users, as they are too strange and technical. I've tried modifying this a bit, maybe something like this? probably without the "hasInteracted" variable since we are already not showing errors if the parsedAmount === 0n

`InputDisplay.tsx`

```typescript
import React, { useState, useMemo, useEffect } from "react";
import styled from "styled-components";

import { useParams } from "react-router-dom";
import { useDebounce } from "react-use";
import { useAccount } from "wagmi";

import { useSortitionModuleGetJurorBalance, usePnkBalanceOf } from "hooks/contracts/generated";
import { useParsedAmount } from "hooks/useParsedAmount";
import { commify, uncommify } from "utils/commify";
import { formatPNK, roundNumberDown } from "utils/format";
import { isUndefined } from "utils/index";

import { NumberInputField } from "components/NumberInputField";

import StakeWithdrawButton, { ActionType } from "./StakeWithdrawButton";

const StyledField = styled(NumberInputField)`
  height: fit-content;
`;

const LabelArea = styled.div`
  display: flex;
  justify-content: space-between;
`;

const StyledLabel = styled.label`
  color: ${({ theme }) => theme.primaryBlue};
  cursor: pointer;
`;

const InputArea = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
  width: 100%;
`;

const InputFieldAndButton = styled.div`
  display: flex;
  flex-direction: row;
  width: 100%;
`;

const EnsureChainContainer = styled.div`
  button {
    height: 45px;
    border: 1px solid ${({ theme }) => theme.stroke};
  }
`;

interface IInputDisplay {
  action: ActionType;
  isSending: boolean;
  setIsSending: (arg0: boolean) => void;
  setIsPopupOpen: (arg0: boolean) => void;
  amount: string;
  setAmount: (arg0: string) => void;
}

const InputDisplay: React.FC<IInputDisplay> = ({
  action,
  isSending,
  setIsSending,
  setIsPopupOpen,
  amount,
  setAmount,
}) => {
  const [debouncedAmount, setDebouncedAmount] = useState("");
  const [hasInteracted, setHasInteracted] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | undefined>();
  useDebounce(() => setDebouncedAmount(amount), 500, [amount]);
  const parsedAmount = useParsedAmount(uncommify(debouncedAmount) as `${number}`);

  const { id } = useParams();
  const { address } = useAccount();
  const { data: balance } = usePnkBalanceOf({
    enabled: !isUndefined(address),
    args: [address ?? "0x"],
    watch: true,
  });
  const parsedBalance = formatPNK(balance ?? 0n, 0, true);
  const { data: jurorBalance } = useSortitionModuleGetJurorBalance({
    enabled: !isUndefined(address),
    args: [address!, BigInt(id!)],
    watch: true,
  });
  const parsedStake = formatPNK(jurorBalance?.[2] || 0n, 0, true);
  const isStaking = useMemo(() => action === ActionType.stake, [action]);

  useEffect(() => {
    if (!hasInteracted || parsedAmount === 0n) {
      setErrorMsg(undefined);
    } else if (isStaking && balance && parsedAmount > balance) {
      setErrorMsg("Insufficient balance to stake this amount");
    } else if (!isStaking && jurorBalance && parsedAmount > jurorBalance[2]) {
      setErrorMsg("Insufficient staked amount to withdraw this amount");
    } else {
      setErrorMsg(undefined);
    }
  }, [hasInteracted, parsedAmount, isStaking, balance, jurorBalance]);

  return (
    <>
      <LabelArea>
        <label>{`Available ${isStaking ? parsedBalance : parsedStake} PNK`}</label>
        <StyledLabel
          onClick={() => {
            const amount = isStaking ? parsedBalance : parsedStake;
            setAmount(amount);
            setHasInteracted(true);
          }}
        >
          {isStaking ? "Stake" : "Withdraw"} all
        </StyledLabel>
      </LabelArea>
      <InputArea>
        <InputFieldAndButton>
          <StyledField
            value={uncommify(amount)}
            onChange={(e) => {
              setAmount(e);
              setHasInteracted(true);
            }}
            placeholder={isStaking ? "Amount to stake" : "Amount to withdraw"}
            message={errorMsg ?? undefined}
            variant={!isUndefined(errorMsg) ? "error" : "info"}
            formatter={(number: string) => commify(roundNumberDown(Number(number)))}
          />
          <EnsureChainContainer>
            <StakeWithdrawButton
              {...{
                parsedAmount,
                action,
                setAmount,
                isSending,
                setIsSending,
                setIsPopupOpen,
                setErrorMsg,
                hasInteracted,
                setHasInteracted,
              }}
            />
          </EnsureChainContainer>
        </InputFieldAndButton>
      </InputArea>
    </>
  );
};

export default InputDisplay;
```

`StakeWithdrawButton.tsx`

```typescript
import React, { useMemo } from "react";

import { useParams } from "react-router-dom";
import { useAccount, usePublicClient } from "wagmi";

import { Button } from "@kleros/ui-components-library";

import {
  usePnkBalanceOf,
  usePnkIncreaseAllowance,
  usePreparePnkIncreaseAllowance,
  usePnkAllowance,
  getKlerosCore,
  useKlerosCoreSetStake,
  usePrepareKlerosCoreSetStake,
  useSortitionModuleGetJurorBalance,
} from "hooks/contracts/generated";
import { useCourtDetails } from "hooks/queries/useCourtDetails";
import { isUndefined } from "utils/index";
import { wrapWithToast } from "utils/wrapWithToast";

import { EnsureChain } from "components/EnsureChain";

export enum ActionType {
  allowance = "allowance",
  stake = "stake",
  withdraw = "withdraw",
}

interface IActionButton {
  isSending: boolean;
  parsedAmount: bigint;
  action: ActionType;
  setIsSending: (arg0: boolean) => void;
  setAmount: (arg0: string) => void;
  setIsPopupOpen: (arg0: boolean) => void;
  setErrorMsg: (arg0: string | undefined) => void;
  hasInteracted: boolean;
  setHasInteracted: (arg0: boolean) => void;
}

const StakeWithdrawButton: React.FC<IActionButton> = ({
  parsedAmount,
  action,
  isSending,
  setIsSending,
  setIsPopupOpen,
  setHasInteracted,
}) => {
  const { id } = useParams();
  const { address } = useAccount();
  const klerosCore = getKlerosCore({});
  const { data: courtDetails } = useCourtDetails(id);
  const { data: balance } = usePnkBalanceOf({
    enabled: !isUndefined(address),
    args: [address!],
    watch: true,
  });
  const { data: jurorBalance } = useSortitionModuleGetJurorBalance({
    enabled: !isUndefined(address),
    args: [address ?? "0x", BigInt(id ?? 0)],
    watch: true,
  });
  const { data: allowance } = usePnkAllowance({
    enabled: !isUndefined(address),
    args: [address ?? "0x", klerosCore.address],
    watch: true,
  });
  const publicClient = usePublicClient();

  const isStaking = action === ActionType.stake;
  const isAllowance = isStaking && !isUndefined(allowance) && allowance < parsedAmount;

  const targetStake = useMemo(() => {
    if (jurorBalance) {
      if (isAllowance) {
        return parsedAmount;
      } else if (isStaking) {
        return jurorBalance[2] + parsedAmount;
      } else {
        return jurorBalance[2] - parsedAmount;
      }
    }
    return 0n;
  }, [jurorBalance, parsedAmount, isAllowance, isStaking]);

  const { config: increaseAllowanceConfig } = usePreparePnkIncreaseAllowance({
    enabled: isAllowance && !isUndefined(klerosCore) && !isUndefined(targetStake) && !isUndefined(allowance),
    args: [klerosCore?.address, BigInt(targetStake ?? 0) - BigInt(allowance ?? 0)],
  });
  const { writeAsync: increaseAllowance } = usePnkIncreaseAllowance(increaseAllowanceConfig);
  const handleAllowance = () => {
    if (!isUndefined(increaseAllowance)) {
      setIsSending(true);
      wrapWithToast(async () => await increaseAllowance().then((response) => response.hash), publicClient).finally(
        () => {
          setIsSending(false);
      [...]

2024-05-21 08:37 UTC, Harman-singh-waraich commented
Negative numbers not handled in withdraw. Fine for staking.

<img width="647" alt="Screenshot 2024-05-21 at 2 04 22 PM" src="https://github.com/kleros/kleros-v2/assets/51452848/2409bfb1-4609-45c5-9db9-df726b56f8d3">

2024-05-21 08:47 UTC, Harman-singh-waraich commented
> Errors do not go away when you interact with the InputDisplay Field, I think we should rethink this in another way. I think contract errors should not be displayed for users, as they are too strange and technical. I've tried modifying this a bit, maybe something like this? probably without the "hasInteracted" variable since we are already not showing errors if the parsedAmount === 0n
> 
> `InputDisplay.tsx`
> 
> ```ts
> import React, { useState, useMemo, useEffect } from "react";
> import styled from "styled-components";
> 
> import { useParams } from "react-router-dom";
> import { useDebounce } from "react-use";
> import { useAccount } from "wagmi";
> 
> import { useSortitionModuleGetJurorBalance, usePnkBalanceOf } from "hooks/contracts/generated";
> import { useParsedAmount } from "hooks/useParsedAmount";
> import { commify, uncommify } from "utils/commify";
> import { formatPNK, roundNumberDown } from "utils/format";
> import { isUndefined } from "utils/index";
> 
> import { NumberInputField } from "components/NumberInputField";
> 
> import StakeWithdrawButton, { ActionType } from "./StakeWithdrawButton";
> 
> const StyledField = styled(NumberInputField)`
>   height: fit-content;
> `;
> 
> const LabelArea = styled.div`
>   display: flex;
>   justify-content: space-between;
> `;
> 
> const StyledLabel = styled.label`
>   color: ${({ theme }) => theme.primaryBlue};
>   cursor: pointer;
> `;
> 
> const InputArea = styled.div`
>   display: flex;
>   flex-direction: column;
>   align-items: center;
>   gap: 12px;
>   width: 100%;
> `;
> 
> const InputFieldAndButton = styled.div`
>   display: flex;
>   flex-direction: row;
>   width: 100%;
> `;
> 
> const EnsureChainContainer = styled.div`
>   button {
>     height: 45px;
>     border: 1px solid ${({ theme }) => theme.stroke};
>   }
> `;
> 
> interface IInputDisplay {
>   action: ActionType;
>   isSending: boolean;
>   setIsSending: (arg0: boolean) => void;
>   setIsPopupOpen: (arg0: boolean) => void;
>   amount: string;
>   setAmount: (arg0: string) => void;
> }
> 
> const InputDisplay: React.FC<IInputDisplay> = ({
>   action,
>   isSending,
>   setIsSending,
>   setIsPopupOpen,
>   amount,
>   setAmount,
> }) => {
>   const [debouncedAmount, setDebouncedAmount] = useState("");
>   const [hasInteracted, setHasInteracted] = useState(false);
>   const [errorMsg, setErrorMsg] = useState<string | undefined>();
>   useDebounce(() => setDebouncedAmount(amount), 500, [amount]);
>   const parsedAmount = useParsedAmount(uncommify(debouncedAmount) as `${number}`);
> 
>   const { id } = useParams();
>   const { address } = useAccount();
>   const { data: balance } = usePnkBalanceOf({
>     enabled: !isUndefined(address),
>     args: [address ?? "0x"],
>     watch: true,
>   });
>   const parsedBalance = formatPNK(balance ?? 0n, 0, true);
>   const { data: jurorBalance } = useSortitionModuleGetJurorBalance({
>     enabled: !isUndefined(address),
>     args: [address!, BigInt(id!)],
>     watch: true,
>   });
>   const parsedStake = formatPNK(jurorBalance?.[2] || 0n, 0, true);
>   const isStaking = useMemo(() => action === ActionType.stake, [action]);
> 
>   useEffect(() => {
>     if (!hasInteracted || parsedAmount === 0n) {
>       setErrorMsg(undefined);
>     } else if (isStaking && balance && parsedAmount > balance) {
>       setErrorMsg("Insufficient balance to stake this amount");
>     } else if (!isStaking && jurorBalance && parsedAmount > jurorBalance[2]) {
>       setErrorMsg("Insufficient staked amount to withdraw this amount");
>     } else {
>       setErrorMsg(undefined);
>     }
>   }, [hasInteracted, parsedAmount, isStaking, balance, jurorBalance]);
> 
>   return (
>     <>
>       <LabelArea>
>         <label>{`Available ${isStaking ? parsedBalance : parsedStake} PNK`}</label>
>         <StyledLabel
>           onClick={() => {
>             const amount = isStaking ? parsedBalance : parsedStake;
>             setAmount(amount);
>             setHasInteracted(true);
>           }}
>         >
>           {isStaking ? "Stake" : "Withdraw"} all
>         </StyledLabel>
>       </LabelArea>
>       <InputArea>
>         <InputFieldAndButton>
>           <StyledField
>             value={uncommify(amount)}
>             onChange={(e) => {
>               setAmount(e);
>               setHasInteracted(true);
>             }}
>             placeholder={isStaking ? "Amount to stake" : "Amount to withdraw"}
>             message={errorMsg ?? undefined}
>             variant={!isUndefined(errorMsg) ? "error" : "info"}
>             formatter={(number: string) => commify(roundNumberDown(Number(number)))}
>           />
>           <EnsureChainContainer>
>             <StakeWithdrawButton
>               {...{
>                 parsedAmount,
>                 action,
>                 setAmount,
>                 isSending,
>                 setIsSending,
>                 setIsPopupOpen,
>                 setErrorMsg,
>                 hasInteracted,
>                 setHasInteracted,
>               }}
>             />
>           </EnsureChainContainer>
>         </InputFieldAndButton>
>       </InputArea>
>     </>
>   );
> };
> 
> export default InputDisplay;
> ```
> 
> `StakeWithdrawButton.tsx`
> 
> ```ts
> import React, { useMemo } from "react";
> 
> import { useParams } from "react-router-dom";
> import { useAccount, usePublicClient } from "wagmi";
> 
> import { Button } from "@kleros/ui-components-library";
> 
> import {
>   usePnkBalanceOf,
>   usePnkIncreaseAllowance,
>   usePreparePnkIncreaseAllowance,
>   usePnkAllowance,
>   getKlerosCore,
>   useKlerosCoreSetStake,
>   usePrepareKlerosCoreSetStake,
>   useSortitionModuleGetJurorBalance,
> } from "hooks/contracts/generated";
> import { useCourtDetails } from "hooks/queries/useCourtDetails";
> import { isUndefined } from "utils/index";
> import { wrapWithToast } from "utils/wrapWithToast";
> 
> import { EnsureChain } from "components/EnsureChain";
> 
> export enum ActionType {
>   allowance = "allowance",
>   stake = "stake",
>   withdraw = "withdraw",
> }
> 
> interface IActionButton {
>   isSending: boolean;
>   parsedAmount: bigint;
>   action: ActionType;
>   setIsSending: (arg0: boolean) => void;
>   setAmount: (arg0: string) => void;
>   setIsPopupOpen: (arg0: boolean) => void;
>   setErrorMsg: (arg0: string | undefined) => void;
>   hasInteracted: boolean;
>   setHasInteracted: (arg0: boolean) => void;
> }
> 
> const StakeWithdrawButton: React.FC<IActionButton> = ({
>   parsedAmount,
>   action,
>   isSending,
>   setIsSending,
>   setIsPopupOpen,
>   setHasInteracted,
> }) => {
>   const { id } = useParams();
>   const { address } = useAccount();
>   const klerosCore = getKlerosCore({});
>   const { data: courtDetails } = useCourtDetails(id);
>   const { data: balance } = usePnkBalanceOf({
>     enabled: !isUndefined(address),
>     args: [address!],
>     watch: true,
>   });
>   const { data: jurorBalance } = useSortitionModuleGetJurorBalance({
>     enabled: !isUndefined(address),
>     args: [address ?? "0x", BigInt(id ?? 0)],
>     watch: true,
>   });
>   const { data: allowance } = usePnkAllowance({
>     enabled: !isUndefined(address),
>     args: [address ?? "0x", klerosCore.address],
>     watch: true,
>   });
>   const publicClient = usePublicClient();
> 
>   const isStaking = action === ActionType.stake;
>   const isAllowance = isStaking && !isUndefined(allowance) && allowance < parsedAmount;
> 
>   const targetStake = useMemo(() => {
>     if (jurorBalance) {
>       if (isAllowance) {
>         return parsedAmount;
>       } else if (isStaking) {
>         return jurorBalance[2] + parsedAmount;
>       } else {
>         return jurorBalance[2] - parsedAmount;
>       }
>     }
>     return 0n;
>   }, [jurorBalance, parsedAmount, isAllowance, isStaking]);
> 
>   const { config: increaseAllowanceConfig } = usePreparePnkIncreaseAllowance({
>     enabled: isAllowance && !isUndefined(klerosCore) && !isUndefined(targetStake) [...]

2024-05-24 10:41 UTC, kemuru commented
continued on #1585

2024-05-24 10:41 UTC, closed without merging