Feat/devtools ruler functionality
kleros/kleros-v2 pull request #1694
Opened 2024-09-25 08:45 UTC by Harman-singh-waraich

2024-09-27 10:00 UTC, Harman-singh-waraich commented on web-devtools/src/utils/shortenAddress.ts
> +}
we are already checking that with :
>    if (formattedAddress.length <= 13) {  // 6 + 3 + 4
      return formattedAddress;  // Return the full address if it's too short to shorten
    }

2024-09-27 10:03 UTC, Harman-singh-waraich commented on web-devtools/src/hooks/useLocalStorage.ts
> +}
The return type will be inferred itself right, there is no hard need to type explicitly

2024-09-27 10:05 UTC, Harman-singh-waraich commented on web-devtools/src/components/ConnectWallet/index.tsx
> +  }, [switchChain]);
Not needed at this moment since the switch chain button will still show, which would mean the chain did not switch.

2024-09-27 10:07 UTC, Harman-singh-waraich commented on web-devtools/package.json
> +    "@typescript-eslint/utils": "^5.62.0",
It is being used here : https://github.com/kleros/kleros-v2/blob/db886f02e5c2b4edb7135bdcc932752a7c2d461e/web-devtools/src/app/(main)/layout.tsx#L17

2024-09-27 10:08 UTC, Harman-singh-waraich commented on web-devtools/src/app/(main)/ruler/RulingModes.tsx
> +          defaultChecked={arbitrableSettings?.rulingMode === RULING_MODE.AutomaticRandom}
Fixed 👍

2024-09-30 11:21 UTC, alcercu requested changes
Maybe let's add an info card next to each section 🤔 I think that could help devs.
![image](https://github.com/user-attachments/assets/33501e57-38cb-451f-81bd-bedf0c271f07)

If you can only change this settings when you are in the automatic preset, I think it's better to show them as disabled or hidden
![image](https://github.com/user-attachments/assets/04ca635a-4703-400e-ada2-31c752698843)

Here I think we could make the input field the same size as the component, and then add padding to the left so that the prompt is where we want. That way the shadow highlight will look better I think, surrounding the whole element 🤔 also, I believe the number input on the ui-package doesn't show the grey arrows, right? 🤔 
![image](https://github.com/user-attachments/assets/2cce2384-683e-4c81-904a-6f30866a3d98)

And I know this is how we have been doing it in the court, but I think we have too many "Connect" buttons here 🤔 could we do a similar approach to what etherscan does (i.e. disable the buttons and show a connect button at the top) without too much changes?
![image](https://github.com/user-attachments/assets/b2963fd6-0664-4cb8-927b-405342b88cf7)
![image](https://github.com/user-attachments/assets/91b5234f-35dd-40dc-8ded-b708aa76176d)

2024-10-07 07:47 UTC, Harman-singh-waraich commented on web-devtools/src/app/(main)/ruler/ManualRuling.tsx
> +  }, [publicClient, executeConfig, manualModeConfig, arbitrableSettings, changeToManualMode, executeRuling]);
It is never changed before those statements, so no need to reset. It is already default (false) there

2024-10-07 08:57 UTC, alcercu approved these changes
lgtm

2024-10-07 08:58 UTC, merged