Feat/dispute dates and hashes link
kleros/kleros-v2 pull request #1816
Opened 2024-12-23 11:06 UTC by Harman-singh-waraich

- Adds txn link for dispute creation
- Adds timestamp and txn link for Vote / justification
- Adds txn link for dispute Ruling transaction

2024-12-23 13:30 UTC, kemuru requested changes
1) In the justification part, I would place the date field *after* the justification. The user is first interested in seeing the vote, then the justification, and then the date. (or at least that's how I see it as a juror)

2) font-size of date should be 16px to match the other font sizes around it
<img width="265" alt="image" src="https://github.com/user-attachments/assets/99bab812-d236-472a-97e5-a95c16a406f0" />

3) if in one place we put the txHash and in other place we put the date, we are not being consistent. maybe we could show a "Dispute created (ArrowICON)" or maybe "Date ArrowICON"

CURRENT
<img width="356" alt="image" src="https://github.com/user-attachments/assets/e16a5f52-1eb7-4f86-a1ba-b4620a3fd98b" />

possible other way
<img width="278" alt="image" src="https://github.com/user-attachments/assets/e9fcfde3-5d0f-41c7-af9b-68558b40b66a" />

other possible way
<img width="271" alt="image" src="https://github.com/user-attachments/assets/3b753b3e-16f8-43fa-a104-b4bdcbc35a66" />

2024-12-23 14:50 UTC, kemuru approved these changes

2024-12-23 15:57 UTC, Harman-singh-waraich commented on web/src/components/Verdict/DisputeTimeline.tsx
> +            / {votingHistory?.dispute?.rounds.at(-1)?.court.name}
rounds array will always atleast one item

2024-12-23 15:57 UTC, kemuru submitted a review, later dismissed

2024-12-23 16:05 UTC, alcercu approved these changes
lgtm

2025-01-07 09:35 UTC, alcercu approved these changes
lgtm

2025-01-07 10:07 UTC, merged