refactor: rng inheritance simplified, removed unused incentive mechanism
kleros/kleros-v2 pull request #233
Opened 2022-08-25 20:32 UTC by jaybuidl

2022-08-29 22:49 UTC, shotaronowhere requested changes
the changes are actually pretty low priority. just some small gas optimization, but might as well

2022-08-29 22:49 UTC, shotaronowhere commented on contracts/src/rng/BlockhashRNG.sol
> +        if (_block < block.number && randomNumbers[_block] == 0) {
no need to check randomNumbers[_block] == 0, this is already known from line 34.

2022-08-29 22:49 UTC, shotaronowhere commented on contracts/src/rng/BlockhashRNG.sol
> +                randomNumbers[_block] = uint256(blockhash(_block));
not a big deal, but would be cheaper to do 
`randomNumber = uint256(blockhash(_block));`
`randomNumbers[_block] = randomNumber;`

and remove line 48. Similarly for the else block.

`randomNumber = uint256(blockhash(block.number - 1));`
`randomNumbers[_block] = randomNumber;`

2022-09-07 09:35 UTC, unknownunknown1 commented on contracts/src/rng/IncrementalNG.sol
> +    function requestRandomness(uint256 _block) external override {
This function is not used anywhere? Do we really want to keep it?

2022-09-07 11:01 UTC, unknownunknown1 approved these changes

2022-09-07 17:03 UTC, merged