Feat(script)/policy ipfs script
kleros/kleros-v2 pull request #639
Opened 2023-03-18 06:39 UTC by Params10

- fix for #588 .
- styling and typing issue solved.
- contract calls commented, can be executed when ready.
- all format supported for netlify function including pdfs.

2023-03-20 11:05 UTC, alcercu requested changes

2023-03-20 11:44 UTC, Params10 commented on contracts/scripts/policyUpdate.ts
> +const AWS = require("aws-sdk");
Updated the required changes.

2023-03-20 11:45 UTC, Params10 commented on contracts/scripts/policyUpdate.ts
> +const formattedDate = `${currentDate.getFullYear()}/${(currentDate.getMonth() + 1)
Updated and followed similar to uploadToIPFS

2023-03-20 11:46 UTC, Params10 commented on contracts/scripts/policyUpdate.ts
> +const uploadFormDataToIPFS = async (data, filename) => {
Renamed the function.

2023-03-20 11:59 UTC, Params10 commented on contracts/scripts/policyUpdate.ts
> +    "0xAF0F49Fe110b48bd512F00d51D141F023c9a9106" // arbitrumgoerli contract address
resolved the issue , now compatible with all chain .

2023-03-20 11:59 UTC, Params10 commented on contracts/scripts/policyUpdate.ts
> +  //--------uncomment once configuration is set in deployments------
removed and resolved the comment issue .

2025-04-15 18:20 UTC, jaybuidl commented
Obsolete

2025-04-15 18:20 UTC, closed without merging